create table ah_csv (
    DOW        date,
    AUT        varchar,
    ACH        varchar,
    SOI        varchar,
    FACC       varchar,
    IDN4       INTEGER,
    NM4        varchar,
    IDN3       INTEGER,
    NM3        varchar,
    IDN2       INTEGER,
    NM2        varchar,
    VYMERA     varchar,
    NUTS1      varchar,
    NUTS1_CODE varchar,
    NUTS2      varchar,
    NUTS2_CODE varchar,
    NUTS3      varchar,
    NUTS3_CODE varchar,
    LAU1       varchar,
    LAU1_CODE  varchar,
    LAU2       varchar,
    LAU2_CODE  varchar
);
